name: Print Message
description: A composite action to print a custom message

inputs: # 外部から渡される値を指定
  message:
    description: 'The message to print'
    required: true
  repeat:
    description: 'The number of times to repeat the message'
    required: false
    default: 1

outputs: # 他のステップやワークフローに値を返せる
  last_message:
    description: 'The last printed message'

runs: # 使用する処理(Shellスクリプトなど)を定義
  using: "composite"
  steps:
    - name: Repeat Message
      shell: bash
      run: |
        for i in ${seq 1 ${{ inputs.repeat }}); do
          echo "${{ inputs.message }}"
        done
        echo "::set-output name=last_message::${{ inputs.message }}"
