name: Reusable Workflow
on:
  workflow_call: # このワークフローを呼び出し可能にする
    inputs:
      greeting:
        type: string
        required: true
        default: Hello, World!
    secrets:
      token:
        required: true

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "${{ inputs.greeting }}!
