name: Main Workflow
on:
  push:
    branches:
      - main

jobs:
  call-reusable:
    uses: ./github/workflows/reusable.yml@main # 同じリポジトリ内のパス
    with:
      greeting: "Hello from Main Workflow"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
