name: Use Composite Action

on:
  push:
    branches:
      - main

jobs:
  call-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Call Print Message Action
        uses: ./github/actions/print-message # Composite Actionをローカルパスで指定
        with:                                # Composite Actionのinputsに値を渡す
          message: "Hello from composite Action"
          repeat: 3

      - name: Use Output from Action
        run: echo "Last message was: ${{ steps.Call_Print_Message_Action.outputs.last_message }}" # outputs: Composite Actionの出力を利用
