name: Use Composite Action

on:
  push:
    branches:
      - main

jobs:
  call-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Call Print Message Action
        id: call_print_message_action
        uses: ./github/actions/print-message # ローカルアクションのパスを指定
        with:
          message: "Hello from composite Action"
          repeat: 3

      - name: Use Output from Action
        run: 'echo "Last message was: ${{ steps.call_print_message_action.outputs.last_message }}"'
